###
POST http://localhost:3002/api/blogs HTTP/1.1
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgdXNlciAyIiwiaWQiOiI2NDk0YWRlZDVkYjRkMDdmN2NmNDdkNjQiLCJpYXQiOjE2ODc0NjYzMjN9.BlehdFVI5AoG9NYWHCLu1AQZp1zeAmp0jPsXCj5Cdcg

{
  "title": "posted by test user 2",
  "author": "Title-22-06-23:57",
  "url": "some url here",
  "likes": 300
  //"userId": "6488c373b3298fc2a35a3161" 
}

###
GET http://localhost:3002/api/blogs HTTP/1.1
Content-Type : application/json

###
DELETE http://localhost:3002/api/blogs/6467aebdf71dbda56e12f7e0 HTTP/1.1


###
PUT http://localhost:3002/api/blogs/64838a49f5a058d3e9f362fb
Content-Type : application/json

{
  "title": "Title 509876",
  "author": "Talha",
  "url": "some url here",
  "likes": 30000
}
