###
GET http://localhost:3002/api/users/ HTTP/1.1


###
POST http://localhost:3002/api/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "test_user3",
    "name": "test user for running tests",
    "password": "test"
}